#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="/etc/sing-box"
INSTALL_DIR="/opt/singbox-rule-ui"
MANAGER_DIR="$CONFIG_DIR/manager"
INSTALL_STATE_FILE="$MANAGER_DIR/install-state"
RADVD_STATE_FILE="$MANAGER_DIR/radvd-state.before-sing-box"
LOG_DIR="/var/log/sing-box-gateway"
LOGROTATE_CONFIG="/etc/logrotate.d/sing-box-gateway"
ROOT_CRONTAB="/etc/crontabs/root"
RULE_UPDATE_CRON_MARKER_BEGIN="# BEGIN sing-box-gateway-ui rule update"
RULE_UPDATE_CRON_MARKER_END="# END sing-box-gateway-ui rule update"
MONITOR_CRON_MARKER_BEGIN="# BEGIN sing-box-gateway-ui runtime monitor"
MONITOR_CRON_MARKER_END="# END sing-box-gateway-ui runtime monitor"
APK_PACKAGES=(bash curl ca-certificates tar gzip python3 nftables iproute2 rsync util-linux coreutils openrc logrotate)
PURGE=0
ASSUME_YES=0

usage() {
  cat <<'EOF'
Usage:
  sudo bash scripts/uninstall.sh [--purge] [--yes]

Default uninstall removes sing-box-gateway-ui OpenRC services, helper scripts,
cron jobs, runtime config, generated rules, UI files, and the bundled sing-box
binary when this installer added it. APK packages that existed before
installation are kept.

Use --purge to also remove /usr/local/bin/sing-box when ownership cannot be
proven from the install state.
EOF
}

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root." >&2
    exit 1
  fi
}

ask_confirm() {
  if [ "$ASSUME_YES" = "1" ]; then
    return 0
  fi
  if [ ! -r /dev/tty ]; then
    echo "No interactive terminal. Re-run with --yes to confirm." >&2
    exit 1
  fi
  prompt="Uninstall sing-box-gateway-ui and remove all files installed by it?"
  if [ "$PURGE" = "1" ]; then
    prompt="PURGE all sing-box-gateway-ui files, configs, and /usr/local/bin/sing-box?"
  fi
  printf "%s [y/N]: " "$prompt" > /dev/tty
  read -r answer < /dev/tty
  case "$answer" in
    y|Y|yes|YES) ;;
    *) echo "Cancelled."; exit 0 ;;
  esac
}

run_rc_service() {
  if command -v rc-service >/dev/null 2>&1 && [ -x "/etc/init.d/$1" ]; then
    rc-service "$@" >/dev/null 2>&1 || true
  fi
}

run_rc_update_del() {
  if command -v rc-update >/dev/null 2>&1; then
    rc-update del "$1" default >/dev/null 2>&1 || true
  fi
}

cleanup_tproxy_runtime() {
  if command -v nft >/dev/null 2>&1; then
    nft delete table inet singbox_tproxy >/dev/null 2>&1 || true
    nft delete table inet singbox >/dev/null 2>&1 || true
  fi
  ip rule del fwmark 1 table 100 >/dev/null 2>&1 || true
  ip -6 rule del fwmark 1 table 100 >/dev/null 2>&1 || true
  ip route flush table 100 >/dev/null 2>&1 || true
  ip -6 route flush table 100 >/dev/null 2>&1 || true
}

state_value() {
  local key="$1" file="$2"
  [ -r "$file" ] || return 0
  awk -F= -v key="$key" '$1 == key { print substr($0, length(key) + 2); exit }' "$file"
}

restore_radvd_state() {
  if ! command -v rc-service >/dev/null 2>&1 || [ ! -x /etc/init.d/radvd ] || [ ! -r "$RADVD_STATE_FILE" ]; then
    return
  fi
  before_enabled="$(state_value enabled "$RADVD_STATE_FILE")"
  before_active="$(state_value active "$RADVD_STATE_FILE")"

  # 只按安装前记录恢复 radvd；没有记录时绝不主动广播 IPv6 默认网关。
  if [ "$before_enabled" = "enabled" ]; then
    rc-update add radvd default >/dev/null 2>&1 || true
  else
    rc-update del radvd default >/dev/null 2>&1 || true
  fi

  if [ "$before_active" = "active" ]; then
    rc-service radvd start >/dev/null 2>&1 || true
  else
    rc-service radvd stop >/dev/null 2>&1 || true
  fi
}

remove_generated_radvd_files() {
  for path in /etc/radvd.conf /etc/radvd.conf.bak.* /etc/radvd.conf.bak-restore-rdnss-*; do
    [ -e "$path" ] || continue
    if head -n 1 "$path" 2>/dev/null | grep -q "Generated by Sing-box UI"; then
      rm -f "$path"
    fi
  done
}

remove_sing_box_binary_if_owned() {
  owner="$(state_value sing_box_binary "$INSTALL_STATE_FILE")"
  if [ "$owner" = "installed" ] || { [ "$owner" = "" ] && [ "$PURGE" = "1" ]; }; then
    # 本安装器新增的二进制：删除。
    rm -f /usr/local/bin/sing-box
  elif [ "$owner" = "replaced" ]; then
    # 安装器覆盖过用户原有二进制：优先恢复备份，让系统回到安装前状态。
    backup="$(state_value sing_box_binary_backup "$INSTALL_STATE_FILE")"
    if [ -n "$backup" ] && [ -f "$backup" ]; then
      if cp -a "$backup" /usr/local/bin/sing-box; then
        rm -f "$backup"
        echo "Restored original sing-box from $backup"
      fi
    else
      echo "WARN: original sing-box backup not found (state=replaced); leaving current binary in place." >&2
    fi
  fi
}

remove_installed_packages_if_owned() {
  if ! command -v apk >/dev/null 2>&1; then
    return
  fi
  case "${SING_BOX_GATEWAY_REMOVE_DEPS:-0}" in
    1|true|TRUE|yes|YES|on|ON) ;;
    *)
      echo "Keeping apk packages. Set SING_BOX_GATEWAY_REMOVE_DEPS=1 to remove installer-added dependencies."
      return
      ;;
  esac
  packages_to_remove=()
  for package in "${APK_PACKAGES[@]}"; do
    if [ "$(state_value "apk_${package}" "$INSTALL_STATE_FILE")" = "absent" ]; then
      packages_to_remove+=("$package")
    fi
  done
  if [ "${#packages_to_remove[@]}" -eq 0 ]; then
    return
  fi
  # 只卸载安装前不存在、由本安装器引入的依赖，避免误删 Alpine 基础组件。
  apk del "${packages_to_remove[@]}" || true
}

remove_crontab_block() {
  local begin="$1" end="$2" tmp
  [ -r "$ROOT_CRONTAB" ] || return 0
  tmp="$(mktemp)"
  awk -v begin="$begin" -v end="$end" '
    $0 == begin { skip = 1; next }
    $0 == end { skip = 0; next }
    skip != 1 { print }
  ' "$ROOT_CRONTAB" > "$tmp"
  install -m 0600 "$tmp" "$ROOT_CRONTAB"
  rm -f "$tmp"
}

parse_args() {
  for arg in "$@"; do
    case "$arg" in
      --purge) PURGE=1 ;;
      -y|--yes) ASSUME_YES=1 ;;
      -h|--help) usage; exit 0 ;;
      *) echo "Unknown option: $arg" >&2; usage >&2; exit 1 ;;
    esac
  done
}

main() {
  parse_args "$@"
  need_root
  ask_confirm

  echo "Stopping OpenRC services..."
  for service in singbox-rule-ui sing-box sing-box-tproxy; do
    run_rc_service "$service" stop
    run_rc_update_del "$service"
  done

  cleanup_tproxy_runtime
  restore_radvd_state

  echo "Removing cron jobs, service files, and helper scripts..."
  remove_crontab_block "$RULE_UPDATE_CRON_MARKER_BEGIN" "$RULE_UPDATE_CRON_MARKER_END"
  remove_crontab_block "$MONITOR_CRON_MARKER_BEGIN" "$MONITOR_CRON_MARKER_END"
  if command -v rc-service >/dev/null 2>&1 && [ -x /etc/init.d/crond ]; then
    rc-service crond restart >/dev/null 2>&1 || true
  fi
  rm -f \
    /etc/init.d/sing-box \
    /etc/init.d/sing-box-tproxy \
    /etc/init.d/singbox-rule-ui \
    /usr/local/sbin/sing-box-tproxy-setup \
    /usr/local/sbin/refresh-sing-box-runtime-config \
    /usr/local/sbin/monitor-sing-box-runtime \
    /usr/local/sbin/refresh-sing-box-tproxy-setup \
    /usr/local/sbin/update-sing-box-rules-jsdelivr \
    /usr/local/bin/sing-box-gateway-info \
    /usr/local/bin/sing-box-gateway-uninstall \
    "$LOGROTATE_CONFIG" \
    /etc/sysctl.d/99-sing-box-tproxy.conf \
    /etc/sysctl.d/98-sing-box-performance.conf \
    /etc/local.d/singbox-qdisc.start
  # 迁移清理：安装器已不再改 NTP（2026-08-13 起完全不介入系统时间子系统），
  # 但装过旧版本的机器上残留着我们写的 /etc/conf.d/ntpd（含 aliyun 源）。
  # ⚠️ 必须先确认是我们写的再删：用户可能有自己的 ntpd 配置，无条件 rm 会误删。
  # 不重启 ntpd：既然我们不再管它，就不该在卸载时打断它的同步状态。
  if [ -f /etc/conf.d/ntpd ] && grep -q "sing-box 网关" /etc/conf.d/ntpd 2>/dev/null; then
    rm -f /etc/conf.d/ntpd
  fi
  # MTU 持久化脚本名带网卡名(set-mtu-<iface>.start)，用通配清理，避免残留脚本
  # 在网卡改名/换网后把新环境 MTU 设错。
  rm -f /etc/local.d/set-mtu-*.start

  remove_generated_radvd_files
  rm -rf "$INSTALL_DIR" "$LOG_DIR"
  remove_sing_box_binary_if_owned
  remove_installed_packages_if_owned
  rm -rf "$CONFIG_DIR"

  echo "Uninstalled."
}

main "$@"
